ARG RUBY_VERSION
ARG DISTRO_NAME=bullseye

FROM ruby:$RUBY_VERSION-slim-$DISTRO_NAME

ENV DEBIAN_FRONTEND=noninteractive

ARG PG_MAJOR
# Common Dependencies
RUN apt-get update -qq && apt-get install -yq --no-install-recommends \
    build-essential \
    gnupg2 \
    curl \
    less \
    git \
    libvips \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install PostgreSQL dependencies
ARG PG_MAJOR
# Add PostgreSQL to sources list
RUN curl -sSL https://www.postgresql.org/media/keys/ACCC4CF8.asc | gpg --dearmor -o /usr/share/keyrings/postgres-archive-keyring.gpg \
  && echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/postgres-archive-keyring.gpg] https://apt.postgresql.org/pub/repos/apt/" bullseye-pgdg main $PG_MAJOR | tee /etc/apt/sources.list.d/postgres.list > /dev/null

RUN apt-get update -qq && apt-get install -yq --no-install-recommends \
    libpq-dev \
    postgresql-client-$PG_MAJOR \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Upgrade RubyGems and install the latest Bundler version
RUN gem update --system && \
    gem install \
    bundler \
    foreman

RUN gem install foreman
# Add Node.js to sources list
ARG NODE_MAJOR
ARG YARN_VERSION
RUN curl -sL https://deb.nodesource.com/setup_$NODE_MAJOR.x | bash -

RUN apt-get install -y --no-install-recommends \
    nodejs \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Install NodeJS and Yarn
RUN npm install -g yarn@$YARN_VERSION

WORKDIR /app

ADD . /app

# Script run when container first starts
COPY bin/dev bin/dev
RUN chmod +x bin/dev

# Document that we're going to expose port 3000
EXPOSE 3000
# Use Bash as the default command
CMD ["/usr/bin/bash"]
